//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tom2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tom2Entities : DbContext
    {
        public tom2Entities()
            : base("name=tom2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admintable> admintables { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<invoicetable> invoicetables { get; set; }
        public virtual DbSet<order_table> order_table { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<usertable> usertables { get; set; }
    }
}
